### ISSUE TITLE
[Warning] You have to dev !

### ISSUE THREAD

**Issue by notFloran** [martin-damien/gyf#19]
... otherwise the project will end up like [hush](https://github.com/nclshart/hush) !

**Comment by martin-damien** [comment]
Ho no !!!!!!!

![game-of-thrones-musical-wmsjvA5UH8Xqo](https://camo.githubusercontent.com/401569f876493bd1f55326a4a3e242a40f245961/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f776d736a76413555483858716f2f67697068792e676966)
